### PR TITLE
add event system

### PR DESCRIPTION
**Pull request by strangeglyph**
Add support for an event system, enabling plugins to react to events outside of commands. The bot now maintains internal queues for each type of event and dispatches these events to registered listeners.

* Add event queues for: `on_ready`, `on_message`, `on_message_edit`, `on_message_delete`, `on_reaction_add`, `on_reaction_remove`
* Split old `on_message` in two methods (logging and command dispatching) and register each as event
* Register old `on_ready` as event

### CODE REVIEW

**Comment by j-holub** [comment]
It looks pretty nice actually, could you explain what impact this will have for people writing modules? How much the current modules would have to be adjusted and how it will change the overall way the bot works?

**Comment by strangeglyph** [comment]
No changes as far as module authors are concerned, except they can now register callbacks at the client.

**Comment by phschon** [comment]
These changes do have impact on module architecture, especially because the command parser is no longer needed. However, I will stall this request as of now and think about an overall change of the base code by adding an event system.

**Comment by strangeglyph** [comment]
Since I didn't remove the command parsing code, everything still works as before. I'd also advice against removing it, because it is a very convenient shorthand. Forcing every module to listen to all messages and parse commands themselves should not be necessary

**Comment by phschon** [comment]
There are merge conflicts. Please rebase your branch.

**Comment by strangeglyph** [comment]
Done

**Comment by j-holub** [comment]
This will not break existing modules, right? But in addition to that it provides more possibilities for modules to for example react to messages, did I get that right?

**Pull request merged**
